### ISSUE TITLE
About brightness values

### ISSUE THREAD

**Issue by ieremies** [WinEunuuchs2Unix/eyesome#5] opened 2020-06-06 13:53 UTC
On the configuration popup, it says my brightness value is 7500,00, but isn't it supposed to be between 1.00 and 0.00? Also it does not seems to take effect when i try the tests, neither with the default value of 7500,00 nor any value between 1.00 and 0.00.

**Comment by WinEunuuchs2Unix** [comment] 2020-06-06 15:23
The brightness for built-in laptop screen is hardware controlled. You need to find the driver name using:

    $ ls /sys/class/backlight
    intel_backlight

In this example make sure `intel_backlight` is setup in eyesome in the **Internal Name** field. You can see allowed max values using:

    $ cat /sys/class/backlight/intel_backlight/max_brightness
    7500

For monitors that are plugged in to a computer they are software controlled using `xrandr` and need values of `1.0` = 100%, `0.85` = 85%, etc. Adjust the controls on your external monitor for the brightest daytime setting, and then use eyesome to decrease brightness at night at say `0.63` which is 63% for one of my external monitors.

**Comment by ieremies** [comment] 2020-06-06 15:42
Hun, okay, i understand it, checked it and it was already configured correctly. Still not doing anything when I test it.

![image](https://user-images.githubusercontent.com/36969625/83948342-120db080-a7f3-11ea-8a93-1a38d4dc3c6d.png)

**Comment by ieremies** [comment] 2020-06-07 15:33
Turns out it was the same problem as #4 , but without an error message.

**Comment by WinEunuuchs2Unix** [comment] 2020-06-09 23:25
Duplicate of #4

**Closed as completed by WinEunuuchs2Unix** 2020-06-09 23:25 UTC
Labels: enhancement
